name = "homeagent"
main = "index.js"
compatibility_date = "2026-10-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "homeagent-db"
database_id = "4af28cc7-61fa-437b-b86c-2886e629d3b2"


[vars]
CRM_PROVIDER = "asari"
